/**
 * seed:export — Regenerate lib/db/src/seed-data.ts from the live database.
 *
 * Run after every data-loading session that adds new verified matches:
 *   pnpm --filter @workspace/db run seed:export
 *
 * The script connects to the database specified by DATABASE_URL, fetches all
 * products ordered by luxuryGroupId then matchId, and writes a fresh
 * seed-data.ts so future migrations start with the full current catalogue.
 */

import { db, pool } from "./index";
import { productsTable } from "./schema";
import { asc } from "drizzle-orm";
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

function formatValue(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return String(value);
  if (typeof value === "string") {
    const escaped = value
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/\t/g, "\\t");
    return `"${escaped}"`;
  }
  return JSON.stringify(value);
}

function formatProduct(product: Record<string, unknown>): string {
  const fields = [
    "name",
    "brand",
    "price",
    "imageUrl",
    "affiliateLink",
    "category",
    "type",
    "matchId",
    "matchScore",
    "formato",
    "unitaMisura",
    "dupeTier",
    "luxuryGroupId",
    "aiMatchReason",
    "isBestGuess",
    "interpretedAs",
  ] as const;

  const lines = fields.map((field) => `    ${field}: ${formatValue(product[field])},`);
  return `  {\n${lines.join("\n")}\n  }`;
}

async function exportSeed() {
  console.log("[seed:export] Fetching products from database…");

  const products = await db
    .select()
    .from(productsTable)
    .orderBy(
      asc(productsTable.luxuryGroupId),
      asc(productsTable.matchId),
      asc(productsTable.id)
    );

  console.log(`[seed:export] Found ${products.length} products.`);

  const productBlocks = products.map((p) =>
    formatProduct(p as unknown as Record<string, unknown>)
  );

  const output = [
    `import type { InsertProduct } from "./schema";`,
    ``,
    `// Auto-generated by \`pnpm --filter @workspace/db run seed:export\``,
    `// Run this script after every data-loading session to keep the seed up to date.`,
    `// Last exported: ${new Date().toISOString()}`,
    `// Total products: ${products.length}`,
    ``,
    `export const SEED_PRODUCTS: InsertProduct[] = [`,
    productBlocks.join(",\n"),
    `];`,
    ``,
  ].join("\n");

  const outPath = join(__dirname, "seed-data.ts");
  writeFileSync(outPath, output, "utf-8");

  console.log(`[seed:export] Written to ${outPath}`);
  await pool.end();
}

exportSeed().catch((err) => {
  console.error("[seed:export] Error:", err);
  process.exit(1);
});
